leankoala_integration_koala_ping_homepage:
    path:     /p/{project}/integrations/koalaping/
    defaults: { _controller: LeanKoalaIntegrationKoalaPingBundle:Default:index }


leankoala_integration_koala_ping_store:
    path:     /p/{project}/integrations/koalaping/store
    defaults: { _controller: LeanKoalaIntegrationKoalaPingBundle:Default:store }

leankoala_integration_koala_ping_rest:
    path:     /p/integrations/koalaping/rest/
    defaults: { _controller: LeanKoalaIntegrationKoalaPingBundle:Default:restGetSystems }


leankoala_integration_koala_ping_rest_project:
    path:     /p/{project}/integrations/koalaping/rest/
    defaults: { _controller: LeanKoalaIntegrationKoalaPingBundle:Default:restGetSystemsForProject }
