leankoala_integration_js_error_scanner_homepage:
    path:     /p/{project}/integrations/jserrorscanner/
    defaults: { _controller: LeanKoalaIntegrationJsErrorScannerBundle:Default:index }

leankoala_integration_js_error_scanner_store:
    path:     /p/{project}/integrations/jserrorscanner/store/
    defaults: { _controller: LeanKoalaIntegrationJsErrorScannerBundle:Default:store }

leankoala_integration_js_error_scanner_rest:
    path:     /p/integrations/jserrorscanner/rest/
    defaults: { _controller: LeanKoalaIntegrationJsErrorScannerBundle:Default:restGetSystems }
