leankoala_integration_site_info_homepage:
    path:     /p/{project}/integrations/siteinfo/
    defaults: { _controller: LeanKoalaIntegrationSiteInfoBundle:Default:index }

leankoala_integration_site_info_store:
    path:     /p/{project}/integrations/siteinfo/store/
    defaults: { _controller: LeanKoalaIntegrationSiteInfoBundle:Default:store }

leankoala_integration_site_info_rest:
    path:     /p/integrations/siteinfo/rest/
    defaults: { _controller: LeanKoalaIntegrationSiteInfoBundle:Default:restGetSystems }
