koalamon_integration_site_info_homepage:
    path:     /p/{project}/integrations/siteinfo/
    defaults: { _controller: KoalamonIntegrationSiteInfoBundle:Default:index }

koalamon_integration_site_info_store:
    path:     /p/{project}/integrations/siteinfo/store/
    defaults: { _controller: KoalamonIntegrationSiteInfoBundle:Default:store }

koalamon_integration_site_info_rest:
    path:     /p/integrations/siteinfo/rest/
    defaults: { _controller: KoalamonIntegrationSiteInfoBundle:Default:restGetSystems }
