koalamon_integration_missing_request_homepage:
    path:     /p/{project}/integration/missingrequest/
    defaults: { _controller: KoalamonIntegrationMissingRequestBundle:Default:index }

koalamon_integration_missing_request_collection_new:
    path:     /p/{project}/integration/missingrequest/collection/new
    defaults: { _controller: KoalamonIntegrationMissingRequestBundle:Collection:new }

koalamon_integration_missing_request_collection_edit:
    path:     /p/{project}/integration/missingrequest/collection/edit/{collection}/
    defaults: { _controller: KoalamonIntegrationMissingRequestBundle:Collection:edit }

koalamon_integration_missing_request_collection_store:
    path:     /p/{project}/integration/missingrequest/collection/store
    defaults: { _controller: KoalamonIntegrationMissingRequestBundle:Collection:store }

koalamon_integration_missing_request_collection_delete:
    path:     /p/{project}/integration/missingrequest/collection/delete/{collection}/
    defaults: { _controller: KoalamonIntegrationMissingRequestBundle:Collection:delete }

koalamon_integration_missing_request_system_edit:
    path:     /p/{project}/integration/missingrequest/system/edit/{system}/
    defaults: { _controller: KoalamonIntegrationMissingRequestBundle:System:edit }

koalamon_integration_missing_request_system_store:
    path:     /p/{project}/integration/missingrequest/system/store/{system}/
    defaults: { _controller: KoalamonIntegrationMissingRequestBundle:System:store }

koalamon_integration_missing_request_system_rest:
    path:     /p/integration/missingrequest/rest/config
    defaults: { _controller: KoalamonIntegrationMissingRequestBundle:Rest:getConfig }
