leankoala_integration_google_page_speed_homepage:
    path:     /p/{project}/integrations/googlepagespeed/
    defaults: { _controller: LeanKoalaIntegrationGooglePageSpeedBundle:Default:index }

leankoala_integration_google_page_speed_store:
    path:     /p/{project}/integrations/googlepagespeed/store/
    defaults: { _controller: LeanKoalaIntegrationGooglePageSpeedBundle:Default:store }

leankoala_integration_google_page_speed_rest:
    path:     /p/integrations/googlepagespeed/rest/
    defaults: { _controller: LeanKoalaIntegrationGooglePageSpeedBundle:Default:restGetSystems }
