leankoala_integration_smoke_basic_rest:
    path:     /p/integrations/smokebasic/rest/
    defaults: { _controller: LeanKoalaIntegrationSmokeBasicBundle:Default:restGetSystems }

leankoala_integration_smoke_basic_homepage:
    path:     /p/{project}/integrations/smokebasic/
    defaults: { _controller: LeanKoalaIntegrationSmokeBasicBundle:Default:index }

leankoala_integration_smoke_basic_store:
    path:     /p/{project}/integrations/smokebasic/store
    defaults: { _controller: LeanKoalaIntegrationSmokeBasicBundle:Default:store }

leankoala_integration_smoke_basic_config_project:
    path:     /p/{project}/integrations/smokebasic/config/{system}/
    defaults: { _controller: LeanKoalaIntegrationSmokeBasicBundle:Config:project }

leankoala_integration_smoke_basic_config:
    path:     /p/integrations/smokebasic/config/
    defaults: { _controller: LeanKoalaIntegrationSmokeBasicBundle:Config:index }