koalamon_integration_smoke_config_project:
    path:     /p/{project}/integrations/smoke/config/
    defaults: { _controller: KoalamonIntegrationSmokeBundle:Config:project }

koalamon_integration_smoke_config:
    path:     /p/integrations/smoke/config/
    defaults: { _controller: KoalamonIntegrationSmokeBundle:Config:index }

# LittleSEO

koalamon_integration_smoke_seo_homepage:
    path:     /p/{project}/integrations/smoke/seo/
    defaults: { _controller: KoalamonIntegrationSmokeBundle:LittleSeo:index }

koalamon_integration_smoke_seo_store:
    path:     /p/{project}/integrations/smoke/seo/store
    defaults: { _controller: KoalamonIntegrationSmokeBundle:LittleSeo:store }

# XPath Checker

koalamon_integration_smoke_xpath_homepage:
    path:     /p/{project}/integrations/smoke/xpath/
    defaults: { _controller: KoalamonIntegrationSmokeBundle:XPathChecker:index }

koalamon_integration_smoke_xpath_store:
    path:     /p/{project}/integrations/smoke/xpath/store
    defaults: { _controller: KoalamonIntegrationSmokeBundle:XPathChecker:store }


# Json Validator

koalamon_integration_smoke_json_homepage:
    path:     /p/{project}/integrations/smoke/json/
    defaults: { _controller: KoalamonIntegrationSmokeBundle:JsonValidator:index }

koalamon_integration_smoke_json_store:
    path:     /p/{project}/integrations/smoke/json/store
    defaults: { _controller: KoalamonIntegrationSmokeBundle:JsonValidator:store }