services:

    leankoalaintegration.smoke.seo.init:
        class: LeanKoala\Integration\SmokeBundle\EventListener\IntegrationListener
        arguments: [ @service_container ]
        tags:
            - { name: 'kernel.event_listener', event: 'koalamon.integration.init', method: onInit }